spring:
  application:
    name: ragbackend

  datasource:
    url: jdbc:mysql://localhost:3306/rag?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

chroma:
  url: http://localhost:8000



# 这一行很重要，MyBatis-Plus 需要确认实体类的位置
mybatis-plus:
  type-aliases-package: com.example.ragbackend.entity
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
#mybatis-plus:
#  type-aliases-package: com.example.ragbackend.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启控制台 SQL 日志，方便调试
#    map-underscore-to-camel-case: true


langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
#      model-name: deepseek-r1:8b
      model-name: qwen2.5:1.5b
      temperature: 0.7
  dashscope:
    embedding-model:
      api-key: ${DASHSCOPE_API_KEY:sk-b2b8cafb6e6b45e3a221c4e721dce7ad}
      model-name: text-embedding-v4
      batch-size: 10

logging:
  level:
    com.example.ragbackend: INFO
    com.example.ragbackend.mapper: WARN
    com.example.ragbackend.service.impl.DocumentProcessingServiceImpl: DEBUG

minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: rag

# RAG 模块核心参数配置
rag:
  config:
    min-score: 0.6    # 相似度阈值
    max-results: 5    # 最大检索分块数
