CREATE TABLE IF NOT EXISTS knowledge_space (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NULL,
    status TINYINT NOT NULL DEFAULT 1,
    create_by BIGINT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS space_member (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    space_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    join_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_space_member UNIQUE (space_id, user_id),
    CONSTRAINT fk_space_member_space FOREIGN KEY (space_id) REFERENCES knowledge_space(id),
    CONSTRAINT fk_space_member_user FOREIGN KEY (user_id) REFERENCES sys_user(id)
);

CREATE TABLE IF NOT EXISTS folder (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    space_id BIGINT NOT NULL,
    parent_id BIGINT NULL,
    name VARCHAR(100) NOT NULL,
    create_by BIGINT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_folder_space FOREIGN KEY (space_id) REFERENCES knowledge_space(id),
    CONSTRAINT fk_folder_parent FOREIGN KEY (parent_id) REFERENCES folder(id),
    CONSTRAINT fk_folder_creator FOREIGN KEY (create_by) REFERENCES sys_user(id)
);

ALTER TABLE document
    ADD COLUMN IF NOT EXISTS space_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS folder_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS file_type VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS is_deleted TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS delete_time DATETIME NULL,
    ADD COLUMN IF NOT EXISTS error_message VARCHAR(1000) NULL;

ALTER TABLE document
    ADD CONSTRAINT fk_document_space FOREIGN KEY (space_id) REFERENCES knowledge_space(id);

ALTER TABLE document
    ADD CONSTRAINT fk_document_folder FOREIGN KEY (folder_id) REFERENCES folder(id);
